### ISSUE TITLE
BOUNTY: Coverage for widget library bindings and options

### ISSUE THREAD

**Issue by 42Pupusas** [illuminodes/minions#2]
We are using several open source libraries to provide widget components. The WASM bindings and options are very incomplete and coverage needs to be improved. 

Coverage of libraries should at least include: 

- All initial option object configurations
- All event types
- Demo of Yew functional components showcasing Nostr integration

**Comment by 42Pupusas** [comment]
**AG Grid** - [https://www.ag-grid.com/](https://www.ag-grid.com/)

Simple Table Structures only

**Reward**
$50

**Comment by 42Pupusas** [comment]
**Leaflet** - [https://leafletjs.com/](https://leafletjs.com/)

Should showcase real-time geotracking using nostr events

**Reward**
$100

**Comment by 42Pupusas** [comment]
**Full Calendar** - [https://fullcalendar.io/docs](https://fullcalendar.io/docs)

Should be able to use the relay pool context to add new notes as event sources directly

**Reward**
$100

**Comment by omarsoufiane** [comment]
@42Pupusas  Hello,
you can add your bounties on [BountyHub](https://bountyhub.dev) which will attract more contributors, you can accept or decline pull requests that claim the bounty, and if no one solves your bounties, you can retract them and get your money back.

**Comment by rahat2134** [comment]
@42Pupusas Can you please assign this to me, I really want to go with this. It will really help me to start with minions.

Thanks :)

**Comment by rahat2134** [comment]
> @42Pupusas Can you please assign this to me, I really want to go with this. It will really help me to start with minions.
> 
> Thanks :)

@42Pupusas ????

**Comment by rahat2134** [comment]
@42Pupusas Bounty amount will be direct bank transfer or what?

**Comment by 42Pupusas** [comment]
Paid in Bitcoin

**Comment by 42Pupusas** [comment]
Congratulations @rahat2134, another bounty completed!

As always for transparency, please post your Bitcoin address and we will post the transaction when the bounty is paid.

**Comment by rahat2134** [comment]
@42Pupusas 
Here's my Bitcoin address: 
`bc1q530588a6a38s4fc2cc8uk277ygp5mq8700uxlt`

This is a SegWit BTC address on the Bitcoin network.
<img width="516" alt="Screenshot 2024-10-27 at 10 41 57 AM" src="https://github.com/user-attachments/assets/d551cfe4-8706-4a56-9236-5ecd8d7917bf">

Please let me know if you need anything specific/more?

**Comment by 42Pupusas** [comment]
Hey @rahat2134 sorry for delay, little bandwith this week.

Bounty paid for AgGrid completed in #6 :
https://mempool.space/tx/26cf9a70c2ffe63090e8cf1397fde11ffc807ea8f4420f0fc5b863f432d3b7dc

Bounty paid for Leaflet completed in #9:
https://mempool.space/tx/11a5dea297fad180da8f3ead4e152720eb0626eca8b86525bc022d47ee198b80


Really great to see your interest in the bounties! Keep it up!

**Comment by rahat2134** [comment]
@42Pupusas The Last one is remaining, I think - full calendar. You have closed the issue by mistake, I guess. No worries, I have raised the PR for that as well.

**Comment by 42Pupusas** [comment]
@rahat2134 should I pay the same address for the last bounty?

**Comment by rahat2134** [comment]
> @42Pupusas Here's my Bitcoin address: `bc1q530588a6a38s4fc2cc8uk277ygp5mq8700uxlt`
> 
> This is a SegWit BTC address on the Bitcoin network. <img alt="Screenshot 2024-10-27 at 10 41 57 AM" width="516" src="https://private-user-images.githubusercontent.com/136263179/380469509-d551cfe4-8706-4a56-9236-5ecd8d7917bf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MjA0MzAsIm5iZiI6MTczMDgyMDEzMCwicGF0aCI6Ii8xMzYyNjMxNzkvMzgwNDY5NTA5LWQ1NTFjZmU0LTg3MDYtNGE1Ni05MjM2LTVlY2Q4ZDc5MTdiZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwNVQxNTIyMTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMWZkZWZmZDMyMTQwZjZlOWY3NjM0MzI5YmE4NzE3OWY3MzlkYzQ3ZTUyNDE3ZjU2YmNmNjgyMTI3YWZjNTkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.n8RHjSI3bBKQaH3TvD03QvUfV3YzoAy_MlrEf27aXKI">
> 
> Please let me know if you need anything specific/more?


@42Pupusas Yes, same address!!

**Comment by 42Pupusas** [comment]
Bounty Paid for Full Calendar completed in #10:

https://mempool.space/tx/9060d46491fea26e0c81915f330bd62e160e5157d9370cf40cc0161131ec469d

Amazing work @rahat2134

**Comment by rahat2134** [comment]
@42Pupusas Thank you so much for your appreciation for each PR submitted 😀.
Seriously saying it really motivates me!

I am waiting for more issues to tackle and contribute to `minions` :)

**Comment by 42Pupusas** [comment]
And we are motivated by your enthusiasm @rahat2134 !

Don't forget #1  is still open.

Hopefully more bounties will become available soon.
