### ISSUE TITLE
BOUNTY: Toastify Notifications

### ISSUE THREAD

**Issue by 42Pupusas** [illuminodes/minions#3]
Use the 'Toastify' library to create notifications for users regarding relay health and new events.

The basic functionality for this is mostly implemented and it is mainly a UI/UX task of building unobtrusive and informative notifications in any media device context (desktop, tablet, mobile)

**Reward**
$100

**Comment by aliraza556** [comment]
@42Pupusas, Please assign me?

**Comment by 42Pupusas** [comment]
Sorry for the delay, didn't expect contributors so soon. 

Mind sharing how you found the bounty list?

**Comment by rahat2134** [comment]
@aliraza556 are you up with the solution?

**Comment by rahat2134** [comment]
@42Pupusas can you assign me this issue?

**Comment by 42Pupusas** [comment]
@aliraza556 are you still working on this?

please respond or I will assign this issue to @rahat2134 .

@rahat2134  ive assigned you the other issue you requested. you can start with that one and if aliraza does not respond I will transfer this issue to you.

**Comment by aliraza556** [comment]
Hi @42Pupusas, Please assign to @rahat2134.

**Comment by 42Pupusas** [comment]
@rahat2134 great work on this. 

please add a BTC address on this thread, I will comment back with the transaction for the bounty reward

**Comment by rahat2134** [comment]
@42Pupusas 
Here's my Bitcoin address: 
`bc1q530588a6a38s4fc2cc8uk277ygp5mq8700uxlt`

This is a SegWit BTC address on the Bitcoin network.
<img width="516" alt="Screenshot 2024-10-27 at 10 41 57 AM" src="https://github.com/user-attachments/assets/d551cfe4-8706-4a56-9236-5ecd8d7917bf">

Please let me know if you need anything specific/more?

**Comment by 42Pupusas** [comment]
Bounty has been paid @rahat2134 !

$100 @ ~$67600 for a total of ‎0.00147672  BTC

You can check transaction here:

https://mempool.space/tx/2d95aa85d521b5802a0ac5043c4275a8c37e81e188044f7573af654df581fbaa

Hope to see many more contributions from you!
